// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PublishProfileManagerTests.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PublishProfileManagerTests.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FileSystemPublishProfile {
            get {
                return ResourceManager.GetString("FileSystemPublishProfile", resourceCulture);
            }
        }
        
        internal static string FTPPublishProfile {
            get {
                return ResourceManager.GetString("FTPPublishProfile", resourceCulture);
            }
        }
        
        internal static string MSDeployPackagePublishProfile {
            get {
                return ResourceManager.GetString("MSDeployPackagePublishProfile", resourceCulture);
            }
        }
        
        internal static string MSDeployPublishProfile {
            get {
                return ResourceManager.GetString("MSDeployPublishProfile", resourceCulture);
            }
        }
        
        internal static string PublishSettings {
            get {
                return ResourceManager.GetString("PublishSettings", resourceCulture);
            }
        }
        
        internal static string UserPublishProfile {
            get {
                return ResourceManager.GetString("UserPublishProfile", resourceCulture);
            }
        }
        
        internal static string MsDeployFromPublishSettings {
            get {
                return ResourceManager.GetString("MsDeployFromPublishSettings", resourceCulture);
            }
        }
        
        internal static string UserProfileWithEncryptedPassword {
            get {
                return ResourceManager.GetString("UserProfileWithEncryptedPassword", resourceCulture);
            }
        }
    }
}
